#![cfg(feature = "postgres")]

use std::env;
use std::io;
use std::sync::atomic::{AtomicBool, AtomicUsize, Ordering};
use std::sync::{Arc, Mutex};
use std::time::Duration;

use anyhow::{bail, Context, Result};
use data_save_manager::postgres::{DatabaseWriter, PreparedBatch, TransactionBatch, WriteFailure};
use data_save_manager::WriteTimeouts;
use serde_json::{json, Value};
use sqlx::postgres::{PgConnectOptions, PgPoolOptions, PgSslMode};
use sqlx::{PgConnection, PgPool};
use tokio::io::{AsyncReadExt, AsyncWriteExt};
use tokio::net::{TcpListener, TcpStream};
use tokio::sync::{Barrier, Notify};
use tokio::task::{JoinHandle, JoinSet};
use tokio::time::timeout;
use uuid::Uuid;

const WATCHDOG: Duration = Duration::from_secs(10);
const QUEUE: &str = "test_records";
const INSERT_SQL: &str = "INSERT INTO records (value) \
    SELECT value FROM jsonb_to_recordset((SELECT payload FROM data_save_input)) AS r(value integer)";
const UPSERT_COUNT_SQL: &str = ", explicit_rows AS ( \
    INSERT INTO records (id, value) \
    SELECT id, value FROM jsonb_to_recordset((SELECT payload FROM data_save_input)) AS r(id bigint, value integer) \
    WHERE id IS NOT NULL ON CONFLICT (id) DO UPDATE SET value = EXCLUDED.value RETURNING id \
    ), generated_rows AS ( \
    INSERT INTO records (value) \
    SELECT value FROM jsonb_to_recordset((SELECT payload FROM data_save_input)) AS r(id bigint, value integer) \
    WHERE id IS NULL RETURNING id \
    ) SELECT (SELECT count(*) FROM explicit_rows) + (SELECT count(*) FROM generated_rows)";

struct Fixture {
    admin: PgPool,
    pool: PgPool,
    schema: String,
}

impl Fixture {
    async fn new(receipts: bool) -> Result<Self> {
        let url = env::var("DSM_TEST_DATABASE_URL")
            .context("set DSM_TEST_DATABASE_URL explicitly to a local PostgreSQL test database")?;
        let options: PgConnectOptions = url.parse()?;
        if !matches!(options.get_host(), "localhost" | "127.0.0.1" | "::1") {
            bail!("DSM_TEST_DATABASE_URL must target localhost, 127.0.0.1 or ::1");
        }
        let options = options.ssl_mode(PgSslMode::Disable);
        let admin = PgPoolOptions::new()
            .max_connections(2)
            .acquire_timeout(WATCHDOG)
            .connect_with(options.clone())
            .await?;
        let schema = format!("dsm_writer_{}", Uuid::new_v4().simple());
        sqlx::query(&format!("CREATE SCHEMA {schema}"))
            .execute(&admin)
            .await?;
        let pool = PgPoolOptions::new()
            .max_connections(5)
            .acquire_timeout(WATCHDOG)
            .connect_with(options.options([("search_path", schema.as_str())]))
            .await?;
        sqlx::raw_sql(
            "CREATE TABLE records (id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, value integer NOT NULL); \
             CREATE TABLE audit (id bigint GENERATED ALWAYS AS IDENTITY PRIMARY KEY, record_id bigint NOT NULL REFERENCES records(id), value integer NOT NULL)",
        ).execute(&pool).await?;
        let fixture = Self {
            admin,
            pool,
            schema,
        };
        if receipts {
            fixture.create_receipts().await?;
        }
        Ok(fixture)
    }

    async fn create_receipts(&self) -> Result<()> {
        sqlx::query("CREATE TABLE data_save_batches (batch_id uuid PRIMARY KEY, queue text NOT NULL, committed_at timestamptz NOT NULL DEFAULT now())")
            .execute(&self.pool).await?;
        Ok(())
    }

    fn writer(&self, timeouts: WriteTimeouts) -> DatabaseWriter {
        DatabaseWriter::new(self.pool.clone(), timeouts)
    }

    async fn receipt_count(&self, id: Uuid) -> Result<i64> {
        Ok(
            sqlx::query_scalar("SELECT count(*) FROM data_save_batches WHERE batch_id = $1")
                .bind(id)
                .fetch_one(&self.pool)
                .await?,
        )
    }

    async fn counts(&self) -> Result<(i64, i64)> {
        Ok(
            sqlx::query_as("SELECT (SELECT count(*) FROM records), (SELECT count(*) FROM audit)")
                .fetch_one(&self.pool)
                .await?,
        )
    }

    async fn close(self) -> Result<()> {
        self.pool.close().await;
        sqlx::query(&format!("DROP SCHEMA {} CASCADE", self.schema))
            .execute(&self.admin)
            .await?;
        self.admin.close().await;
        Ok(())
    }
}

fn timeouts() -> WriteTimeouts {
    WriteTimeouts::new(
        Duration::from_secs(3),
        Duration::from_secs(2),
        Duration::from_millis(500),
    )
    .unwrap()
}

fn prepared(rows: Value) -> PreparedBatch {
    PreparedBatch::new(INSERT_SQL, rows)
}

fn failure(error: &anyhow::Error, id: Uuid, kind: &str, sqlstate: Option<&str>) {
    let failure = error
        .downcast_ref::<WriteFailure>()
        .expect("structured WriteFailure");
    assert_eq!(failure.batch_id, id);
    assert_eq!(failure.queue, QUEUE);
    assert_eq!(failure.kind, kind, "{error:#}");
    assert_eq!(failure.sqlstate.as_deref(), sqlstate, "{error:#}");
}

enum Pause {
    None,
    Rust,
    Sql,
    Gate {
        entered: Arc<Notify>,
        release: Arc<Notify>,
    },
}

struct PairBatch {
    calls: Arc<AtomicUsize>,
    fail_second: bool,
    pause: Pause,
}

impl PairBatch {
    fn new() -> Self {
        Self {
            calls: Arc::new(AtomicUsize::new(0)),
            fail_second: false,
            pause: Pause::None,
        }
    }
}

impl TransactionBatch for PairBatch {
    async fn execute(&self, connection: &mut PgConnection) -> Result<u64> {
        self.calls.fetch_add(1, Ordering::SeqCst);
        let id: i64 = sqlx::query_scalar("INSERT INTO records(value) VALUES (7) RETURNING id")
            .fetch_one(&mut *connection)
            .await?;
        match &self.pause {
            Pause::None => {}
            Pause::Rust => tokio::time::sleep(Duration::from_secs(30)).await,
            Pause::Sql => {
                sqlx::query("SELECT pg_sleep(30)")
                    .execute(&mut *connection)
                    .await?;
            }
            Pause::Gate { entered, release } => {
                entered.notify_one();
                release.notified().await;
            }
        }
        let value = if self.fail_second { None } else { Some(7_i32) };
        sqlx::query("INSERT INTO audit(record_id, value) VALUES ($1, $2)")
            .bind(id)
            .bind(value)
            .execute(&mut *connection)
            .await?;
        Ok(2)
    }
}

#[tokio::test]
#[ignore = "requires local PostgreSQL"]
async fn readiness_requires_receipt_migration_in_the_selected_schema() -> Result<()> {
    let fixture = Fixture::new(false).await?;
    let writer = fixture.writer(timeouts());
    let error = timeout(WATCHDOG, writer.check_ready()).await?.unwrap_err();
    assert!(format!("{error:#}").contains("data_save_batches"));
    fixture.create_receipts().await?;
    timeout(WATCHDOG, writer.check_ready()).await??;
    drop(writer);
    fixture.close().await
}

#[tokio::test]
#[ignore = "requires local PostgreSQL"]
async fn prepared_replay_does_not_duplicate_generated_rows() -> Result<()> {
    let fixture = Fixture::new(true).await?;
    let writer = fixture.writer(timeouts());
    writer.check_ready().await?;
    let id = Uuid::new_v4();
    for expected in [2, 0] {
        assert_eq!(
            writer
                .write_prepared(id, QUEUE, || Ok(prepared(
                    json!([{ "value": 1 }, { "value": 2 }])
                )))
                .await?,
            expected
        );
    }
    assert_eq!(fixture.counts().await?, (2, 0));
    let receipt: (String, bool) = sqlx::query_as(
        "SELECT queue, committed_at IS NOT NULL FROM data_save_batches WHERE batch_id = $1",
    )
    .bind(id)
    .fetch_one(&fixture.pool)
    .await?;
    assert_eq!(receipt, (QUEUE.to_owned(), true));
    drop(writer);
    fixture.close().await
}

#[tokio::test]
#[ignore = "requires local PostgreSQL"]
async fn counted_prepared_replay_preserves_newer_updates_and_generated_rows() -> Result<()> {
    let fixture = Fixture::new(true).await?;
    let writer = fixture.writer(timeouts());
    let id = Uuid::new_v4();
    let original = json!([{ "id": 10000, "value": 1 }, { "value": 2 }]);
    assert_eq!(
        writer
            .write_prepared(id, QUEUE, || Ok(PreparedBatch::with_count_sql(
                UPSERT_COUNT_SQL,
                original.clone()
            )))
            .await?,
        2
    );
    assert_eq!(
        writer
            .write_prepared(Uuid::new_v4(), QUEUE, || Ok(PreparedBatch::with_count_sql(
                UPSERT_COUNT_SQL,
                json!([{ "id": 10000, "value": 9 }])
            )))
            .await?,
        1
    );
    assert_eq!(
        writer
            .write_prepared(id, QUEUE, || Ok(PreparedBatch::with_count_sql(
                UPSERT_COUNT_SQL,
                original
            )))
            .await?,
        0
    );
    let values: Vec<i32> = sqlx::query_scalar("SELECT value FROM records ORDER BY value")
        .fetch_all(&fixture.pool)
        .await?;
    assert_eq!(values, vec![2, 9]);
    assert_eq!(fixture.receipt_count(id).await?, 1);
    drop(writer);
    fixture.close().await
}

#[tokio::test]
#[ignore = "requires local PostgreSQL"]
async fn failed_prepare_writes_neither_payload_nor_receipt_and_can_retry() -> Result<()> {
    let fixture = Fixture::new(true).await?;
    let writer = fixture.writer(timeouts());
    let id = Uuid::new_v4();
    let error = writer
        .write_prepared(id, QUEUE, || bail!("prepare sentinel"))
        .await
        .unwrap_err();
    failure(&error, id, "serialization_error", None);
    assert_eq!(
        error.downcast_ref::<WriteFailure>().unwrap().stage,
        "prepare"
    );
    assert!(format!("{error:#}").contains("prepare sentinel"));
    assert_eq!(fixture.receipt_count(id).await?, 0);
    assert_eq!(fixture.counts().await?, (0, 0));
    assert_eq!(
        writer
            .write_prepared(id, QUEUE, || Ok(prepared(json!([{ "value": 1 }]))))
            .await?,
        1
    );
    drop(writer);
    fixture.close().await
}

#[tokio::test]
#[ignore = "requires local PostgreSQL"]
async fn prepared_sql_error_rolls_back_payload_and_receipt_for_same_id_retry() -> Result<()> {
    let fixture = Fixture::new(true).await?;
    let writer = fixture.writer(timeouts());
    let id = Uuid::new_v4();
    let error = writer
        .write_prepared(id, QUEUE, || {
            Ok(prepared(json!([{ "value": 1 }, { "value": null }])))
        })
        .await
        .unwrap_err();
    failure(&error, id, "database_error", Some("23502"));
    assert_eq!(fixture.counts().await?, (0, 0));
    assert_eq!(fixture.receipt_count(id).await?, 0);
    assert_eq!(
        writer
            .write_prepared(id, QUEUE, || Ok(prepared(
                json!([{ "value": 1 }, { "value": 2 }])
            )))
            .await?,
        2
    );
    drop(writer);
    fixture.close().await
}

#[tokio::test]
#[ignore = "requires local PostgreSQL"]
async fn transaction_second_statement_failure_rolls_back_first_and_receipt() -> Result<()> {
    let fixture = Fixture::new(true).await?;
    let writer = fixture.writer(timeouts());
    let id = Uuid::new_v4();
    let mut batch = PairBatch::new();
    batch.fail_second = true;
    let error = writer
        .write_transaction(id, QUEUE, &batch)
        .await
        .unwrap_err();
    failure(&error, id, "database_error", Some("23502"));
    assert_eq!(fixture.counts().await?, (0, 0));
    assert_eq!(fixture.receipt_count(id).await?, 0);
    batch.fail_second = false;
    assert_eq!(
        timeout(WATCHDOG, writer.write_transaction(id, QUEUE, &batch)).await??,
        2
    );
    assert_eq!(writer.write_transaction(id, QUEUE, &batch).await?, 0);
    assert_eq!(batch.calls.load(Ordering::SeqCst), 2);
    assert_eq!(fixture.counts().await?, (1, 1));
    assert_eq!(fixture.receipt_count(id).await?, 1);
    drop(writer);
    fixture.close().await
}

#[tokio::test]
#[ignore = "requires local PostgreSQL"]
async fn concurrent_prepared_same_id_inserts_exactly_once() -> Result<()> {
    let fixture = Fixture::new(true).await?;
    let id = Uuid::new_v4();
    let barrier = Arc::new(Barrier::new(2));
    let mut tasks = JoinSet::new();
    for _ in 0..2 {
        let writer = fixture.writer(timeouts());
        let barrier = barrier.clone();
        tasks.spawn(async move {
            writer.check_ready().await?;
            barrier.wait().await;
            writer
                .write_prepared(id, QUEUE, || Ok(prepared(json!([{ "value": 1 }]))))
                .await
        });
    }
    let mut results = Vec::new();
    while let Some(result) = timeout(WATCHDOG, tasks.join_next()).await? {
        results.push(result??);
    }
    results.sort_unstable();
    assert_eq!(results, vec![0, 1]);
    assert_eq!(fixture.counts().await?, (1, 0));
    assert_eq!(fixture.receipt_count(id).await?, 1);
    fixture.close().await
}

#[tokio::test]
#[ignore = "requires local PostgreSQL"]
async fn concurrent_transaction_same_id_executes_callback_exactly_once() -> Result<()> {
    let fixture = Fixture::new(true).await?;
    let id = Uuid::new_v4();
    let entered = Arc::new(Notify::new());
    let release = Arc::new(Notify::new());
    let mut first_batch = PairBatch::new();
    first_batch.pause = Pause::Gate {
        entered: entered.clone(),
        release: release.clone(),
    };
    let first_calls = first_batch.calls.clone();
    let second_batch = PairBatch::new();
    let second_calls = second_batch.calls.clone();
    let first = fixture.writer(timeouts());
    let second = fixture.writer(timeouts());
    first.check_ready().await?;
    second.check_ready().await?;
    let mut tasks = JoinSet::new();
    tasks.spawn(async move { first.write_transaction(id, QUEUE, &first_batch).await });
    timeout(WATCHDOG, entered.notified()).await?;
    let mut replay = Box::pin(second.write_transaction(id, QUEUE, &second_batch));
    assert!(timeout(Duration::from_millis(50), &mut replay)
        .await
        .is_err());
    assert_eq!(second_calls.load(Ordering::SeqCst), 0);
    release.notify_one();
    assert_eq!(timeout(WATCHDOG, tasks.join_next()).await?.unwrap()??, 2);
    assert_eq!(timeout(WATCHDOG, replay).await??, 0);
    assert_eq!(first_calls.load(Ordering::SeqCst), 1);
    assert_eq!(second_calls.load(Ordering::SeqCst), 0);
    assert_eq!(fixture.counts().await?, (1, 1));
    assert_eq!(fixture.receipt_count(id).await?, 1);
    drop(second);
    fixture.close().await
}

async fn lock_timeout_case(transactional: bool) -> Result<()> {
    let fixture = Fixture::new(true).await?;
    let limits = WriteTimeouts::new(
        Duration::from_secs(3),
        Duration::from_secs(2),
        Duration::from_millis(100),
    )?;
    let writer = fixture.writer(limits);
    writer.check_ready().await?;
    let mut held = fixture.pool.begin().await?;
    sqlx::query("LOCK TABLE records IN ACCESS EXCLUSIVE MODE")
        .execute(&mut *held)
        .await?;
    let id = Uuid::new_v4();
    let batch = PairBatch::new();
    let result = if transactional {
        timeout(WATCHDOG, writer.write_transaction(id, QUEUE, &batch)).await?
    } else {
        timeout(
            WATCHDOG,
            writer.write_prepared(id, QUEUE, || Ok(prepared(json!([{ "value": 1 }])))),
        )
        .await?
    };
    held.rollback().await?;
    failure(&result.unwrap_err(), id, "lock_timeout", Some("55P03"));
    assert_eq!(fixture.receipt_count(id).await?, 0);
    assert_eq!(fixture.counts().await?, (0, 0));
    if transactional {
        assert_eq!(
            timeout(WATCHDOG, writer.write_transaction(id, QUEUE, &batch)).await??,
            2
        );
    } else {
        assert_eq!(
            timeout(
                WATCHDOG,
                writer.write_prepared(id, QUEUE, || Ok(prepared(json!([{ "value": 1 }]))))
            )
            .await??,
            1
        );
    }
    drop(writer);
    fixture.close().await
}

#[tokio::test]
#[ignore = "requires local PostgreSQL"]
async fn prepared_lock_timeout_keeps_receipt_retryable() -> Result<()> {
    lock_timeout_case(false).await
}

#[tokio::test]
#[ignore = "requires local PostgreSQL"]
async fn transaction_lock_timeout_keeps_receipt_retryable() -> Result<()> {
    lock_timeout_case(true).await
}

#[tokio::test]
#[ignore = "requires local PostgreSQL"]
async fn prepared_statement_timeout_rolls_back_and_disconnects() -> Result<()> {
    let fixture = Fixture::new(true).await?;
    let limits = WriteTimeouts::new(
        Duration::from_secs(3),
        Duration::from_millis(200),
        Duration::from_millis(100),
    )?;
    let writer = fixture.writer(limits);
    let id = Uuid::new_v4();
    let error = timeout(WATCHDOG, writer.write_prepared(id, QUEUE, || Ok(PreparedBatch::new(
        "INSERT INTO records(value) SELECT 1 FROM data_save_input CROSS JOIN LATERAL pg_sleep(30)", json!([]),
    )))).await?.unwrap_err();
    failure(&error, id, "statement_cancelled", Some("57014"));
    assert_eq!(fixture.counts().await?, (0, 0));
    assert_eq!(fixture.receipt_count(id).await?, 0);
    assert_eq!(
        timeout(
            WATCHDOG,
            writer.write_prepared(id, QUEUE, || Ok(prepared(json!([{ "value": 1 }]))))
        )
        .await??,
        1
    );
    drop(writer);
    fixture.close().await
}

#[tokio::test]
#[ignore = "requires local PostgreSQL"]
async fn transaction_statement_timeout_rolls_back_prior_statement() -> Result<()> {
    let fixture = Fixture::new(true).await?;
    let limits = WriteTimeouts::new(
        Duration::from_secs(3),
        Duration::from_millis(200),
        Duration::from_millis(100),
    )?;
    let writer = fixture.writer(limits);
    let id = Uuid::new_v4();
    let mut batch = PairBatch::new();
    batch.pause = Pause::Sql;
    let error = timeout(WATCHDOG, writer.write_transaction(id, QUEUE, &batch))
        .await?
        .unwrap_err();
    failure(&error, id, "statement_cancelled", Some("57014"));
    assert_eq!(fixture.counts().await?, (0, 0));
    assert_eq!(fixture.receipt_count(id).await?, 0);
    batch.pause = Pause::None;
    assert_eq!(
        timeout(WATCHDOG, writer.write_transaction(id, QUEUE, &batch)).await??,
        2
    );
    drop(writer);
    fixture.close().await
}

#[tokio::test]
#[ignore = "requires local PostgreSQL"]
async fn client_deadline_during_rust_callback_disconnects_and_rolls_back() -> Result<()> {
    let fixture = Fixture::new(true).await?;
    let limits = WriteTimeouts::new(
        Duration::from_millis(500),
        Duration::from_millis(300),
        Duration::from_millis(100),
    )?;
    let writer = fixture.writer(limits);
    writer.check_ready().await?;
    let id = Uuid::new_v4();
    let mut batch = PairBatch::new();
    batch.pause = Pause::Rust;
    let error = timeout(WATCHDOG, writer.write_transaction(id, QUEUE, &batch))
        .await?
        .unwrap_err();
    failure(&error, id, "client_deadline", None);
    assert_eq!(fixture.counts().await?, (0, 0));
    assert_eq!(fixture.receipt_count(id).await?, 0);
    batch.pause = Pause::None;
    assert_eq!(
        timeout(WATCHDOG, writer.write_transaction(id, QUEUE, &batch)).await??,
        2
    );
    assert_eq!(fixture.counts().await?, (1, 1));
    drop(writer);
    fixture.close().await
}

#[tokio::test]
#[ignore = "requires local PostgreSQL"]
async fn external_abort_drops_open_transaction_and_same_writer_can_retry() -> Result<()> {
    let fixture = Fixture::new(true).await?;
    let writer = fixture.writer(timeouts());
    writer.check_ready().await?;
    let entered = Arc::new(Notify::new());
    let mut batch = PairBatch::new();
    batch.pause = Pause::Gate {
        entered: entered.clone(),
        release: Arc::new(Notify::new()),
    };
    let id = Uuid::new_v4();
    let cancelled_writer = writer.clone();
    let mut tasks = JoinSet::new();
    tasks.spawn(async move { cancelled_writer.write_transaction(id, QUEUE, &batch).await });
    timeout(WATCHDOG, entered.notified()).await?;
    tasks.abort_all();
    let result = timeout(WATCHDOG, tasks.join_next()).await?.unwrap();
    assert!(result.unwrap_err().is_cancelled());
    assert_eq!(fixture.counts().await?, (0, 0));
    assert_eq!(fixture.receipt_count(id).await?, 0);
    assert_eq!(
        timeout(
            WATCHDOG,
            writer.write_transaction(id, QUEUE, &PairBatch::new())
        )
        .await??,
        2
    );
    assert_eq!(fixture.counts().await?, (1, 1));
    drop(writer);
    fixture.close().await
}

#[tokio::test]
#[ignore = "requires local PostgreSQL"]
async fn slow_synchronous_prepare_exceeding_deadline_never_submits_sql() -> Result<()> {
    let fixture = Fixture::new(true).await?;
    let proxy = ResponseProxy::start(&fixture.pool.connect_options()).await?;
    let proxy_pool = proxy.pool(&fixture.pool.connect_options());
    let limits = timeouts();
    let writer = DatabaseWriter::new(proxy_pool.clone(), limits);
    writer.check_ready().await?;
    let submitted_before = proxy.submitted_queries.load(Ordering::SeqCst);
    let id = Uuid::new_v4();
    let error = timeout(
        WATCHDOG,
        writer.write_prepared(id, QUEUE, || {
            std::thread::sleep(limits.batch() + Duration::from_millis(200));
            Ok(prepared(json!([{ "value": 1 }])))
        }),
    )
    .await?
    .unwrap_err();
    failure(&error, id, "client_deadline", None);
    assert_eq!(
        error.downcast_ref::<WriteFailure>().unwrap().stage,
        "prepare"
    );
    tokio::time::sleep(Duration::from_millis(100)).await;
    assert_eq!(
        proxy.submitted_queries.load(Ordering::SeqCst),
        submitted_before
    );
    assert_eq!(fixture.counts().await?, (0, 0));
    assert_eq!(fixture.receipt_count(id).await?, 0);
    assert_eq!(
        timeout(
            WATCHDOG,
            writer.write_prepared(id, QUEUE, || Ok(prepared(json!([{ "value": 1 }]))))
        )
        .await??,
        1
    );
    drop(writer);
    proxy_pool.close().await;
    proxy.stop().await;
    fixture.close().await
}

struct ResponseProxy {
    port: u16,
    drop_all: Arc<AtomicBool>,
    drop_commit: Arc<AtomicBool>,
    dropped_commits: Arc<AtomicUsize>,
    submitted_queries: Arc<AtomicUsize>,
    task: JoinHandle<()>,
}

impl ResponseProxy {
    async fn start(upstream: &PgConnectOptions) -> Result<Self> {
        let listener = TcpListener::bind("127.0.0.1:0").await?;
        let port = listener.local_addr()?.port();
        let host = upstream.get_host().to_owned();
        let upstream_port = upstream.get_port();
        let drop_all = Arc::new(AtomicBool::new(false));
        let drop_commit = Arc::new(AtomicBool::new(false));
        let dropped_commits = Arc::new(AtomicUsize::new(0));
        let submitted_queries = Arc::new(AtomicUsize::new(0));
        let all = drop_all.clone();
        let commit = drop_commit.clone();
        let dropped = dropped_commits.clone();
        let submitted = submitted_queries.clone();
        let task = tokio::spawn(async move {
            let mut clients = JoinSet::new();
            loop {
                tokio::select! {
                    client = listener.accept() => {
                        let Ok((client, _)) = client else { break };
                        let host = host.clone();
                        let all = all.clone();
                        let commit = commit.clone();
                        let dropped = dropped.clone();
                        let submitted = submitted.clone();
                        clients.spawn(async move {
                            let server = TcpStream::connect((host.as_str(), upstream_port)).await?;
                            let (mut cr, mut cw) = client.into_split();
                            let (mut sr, mut sw) = server.into_split();
                            tokio::select! {
                                result = async {
                                    let length = cr.read_u32().await?;
                                    if !(8..=16 * 1024 * 1024).contains(&length) {
                                        return Err(io::Error::new(io::ErrorKind::InvalidData, "invalid startup frame"));
                                    }
                                    let mut startup = vec![0; length as usize - 4];
                                    cr.read_exact(&mut startup).await?;
                                    sw.write_all(&length.to_be_bytes()).await?;
                                    sw.write_all(&startup).await?;
                                    loop {
                                        let mut header = [0_u8; 5];
                                        match cr.read_exact(&mut header).await {
                                            Ok(_) => {}
                                            Err(error) if error.kind() == io::ErrorKind::UnexpectedEof => break,
                                            Err(error) => return Err(error),
                                        }
                                        let length = u32::from_be_bytes(header[1..].try_into().unwrap()) as usize;
                                        if !(4..=16 * 1024 * 1024).contains(&length) {
                                            return Err(io::Error::new(io::ErrorKind::InvalidData, "invalid frontend frame"));
                                        }
                                        let mut body = vec![0; length - 4];
                                        cr.read_exact(&mut body).await?;
                                        if matches!(header[0], b'Q' | b'E') {
                                            submitted.fetch_add(1, Ordering::SeqCst);
                                        }
                                        sw.write_all(&header).await?;
                                        sw.write_all(&body).await?;
                                    }
                                    Ok::<(), io::Error>(())
                                } => { result?; }
                                result = async {
                                    let mut suppress = false;
                                    loop {
                                        let mut header = [0_u8; 5];
                                        match sr.read_exact(&mut header).await {
                                            Ok(_) => {}
                                            Err(error) if error.kind() == io::ErrorKind::UnexpectedEof => break,
                                            Err(error) => return Err(error),
                                        }
                                        let length = u32::from_be_bytes(header[1..].try_into().unwrap()) as usize;
                                        if !(4..=16 * 1024 * 1024).contains(&length) {
                                            return Err(io::Error::new(io::ErrorKind::InvalidData, "invalid PostgreSQL frame"));
                                        }
                                        let mut body = vec![0; length - 4];
                                        sr.read_exact(&mut body).await?;
                                        if header[0] == b'C' && body == b"COMMIT\0" && commit.swap(false, Ordering::SeqCst) {
                                            suppress = true;
                                            dropped.fetch_add(1, Ordering::SeqCst);
                                        }
                                        if !suppress && !all.load(Ordering::SeqCst) {
                                            cw.write_all(&header).await?;
                                            cw.write_all(&body).await?;
                                        }
                                    }
                                    Ok::<(), io::Error>(())
                                } => { result?; }
                            }
                            Ok::<(), io::Error>(())
                        });
                    }
                    _ = clients.join_next(), if !clients.is_empty() => {}
                }
            }
        });
        Ok(Self {
            port,
            drop_all,
            drop_commit,
            dropped_commits,
            submitted_queries,
            task,
        })
    }

    fn pool(&self, upstream: &PgConnectOptions) -> PgPool {
        PgPoolOptions::new()
            .max_connections(2)
            .acquire_timeout(WATCHDOG)
            .connect_lazy_with(
                upstream
                    .clone()
                    .host("127.0.0.1")
                    .port(self.port)
                    .ssl_mode(PgSslMode::Disable),
            )
    }

    async fn stop(&self) {
        self.task.abort();
        while !self.task.is_finished() {
            tokio::task::yield_now().await;
        }
    }
}

impl Drop for ResponseProxy {
    fn drop(&mut self) {
        self.task.abort();
    }
}

async fn wait_for_commit(fixture: &Fixture, id: Uuid) -> Result<()> {
    timeout(WATCHDOG, async {
        loop {
            if fixture.receipt_count(id).await? == 1 {
                return Ok::<(), anyhow::Error>(());
            }
            tokio::time::sleep(Duration::from_millis(10)).await;
        }
    })
    .await??;
    Ok(())
}

#[tokio::test]
#[ignore = "requires local PostgreSQL"]
async fn prepared_lost_commit_response_retries_without_duplicate_rows() -> Result<()> {
    let fixture = Fixture::new(true).await?;
    let proxy = ResponseProxy::start(&fixture.pool.connect_options()).await?;
    let proxy_pool = proxy.pool(&fixture.pool.connect_options());
    let writer = DatabaseWriter::new(proxy_pool.clone(), timeouts());
    timeout(WATCHDOG, writer.check_ready()).await??;
    assert_eq!(
        writer
            .write_prepared(Uuid::new_v4(), QUEUE, || Ok(prepared(json!([]))))
            .await?,
        0
    );
    let id = Uuid::new_v4();
    proxy.drop_all.store(true, Ordering::SeqCst);
    let pending_writer = writer.clone();
    let mut tasks = JoinSet::new();
    tasks.spawn(async move {
        pending_writer
            .write_prepared(id, QUEUE, || Ok(prepared(json!([{ "value": 5 }]))))
            .await
    });
    wait_for_commit(&fixture, id).await?;
    let error = timeout(WATCHDOG, tasks.join_next())
        .await?
        .unwrap()?
        .unwrap_err();
    failure(&error, id, "client_deadline", None);
    proxy.drop_all.store(false, Ordering::SeqCst);
    assert_eq!(
        timeout(
            WATCHDOG,
            writer.write_prepared(id, QUEUE, || Ok(prepared(json!([{ "value": 5 }]))))
        )
        .await??,
        0
    );
    assert_eq!(fixture.counts().await?, (1, 0));
    assert_eq!(fixture.receipt_count(id).await?, 1);
    drop(writer);
    proxy_pool.close().await;
    proxy.stop().await;
    fixture.close().await
}

#[tokio::test]
#[ignore = "requires local PostgreSQL"]
async fn transaction_lost_commit_response_does_not_repeat_callback() -> Result<()> {
    let fixture = Fixture::new(true).await?;
    let proxy = ResponseProxy::start(&fixture.pool.connect_options()).await?;
    let proxy_pool = proxy.pool(&fixture.pool.connect_options());
    let writer = DatabaseWriter::new(proxy_pool.clone(), timeouts());
    timeout(WATCHDOG, writer.check_ready()).await??;
    let id = Uuid::new_v4();
    let batch = Arc::new(PairBatch::new());
    proxy.drop_commit.store(true, Ordering::SeqCst);
    let pending_writer = writer.clone();
    let pending_batch = batch.clone();
    let mut tasks = JoinSet::new();
    tasks.spawn(async move {
        pending_writer
            .write_transaction(id, QUEUE, &*pending_batch)
            .await
    });
    wait_for_commit(&fixture, id).await?;
    let error = timeout(WATCHDOG, tasks.join_next())
        .await?
        .unwrap()?
        .unwrap_err();
    failure(&error, id, "client_deadline", None);
    assert_eq!(proxy.dropped_commits.load(Ordering::SeqCst), 1);
    assert_eq!(
        timeout(WATCHDOG, writer.write_transaction(id, QUEUE, &*batch)).await??,
        0
    );
    assert_eq!(batch.calls.load(Ordering::SeqCst), 1);
    assert_eq!(fixture.counts().await?, (1, 1));
    assert_eq!(fixture.receipt_count(id).await?, 1);
    drop(writer);
    proxy_pool.close().await;
    proxy.stop().await;
    fixture.close().await
}

struct TimezoneBatch {
    expected: &'static str,
    pids: Mutex<Vec<i32>>,
    fail: bool,
}

impl TransactionBatch for TimezoneBatch {
    async fn execute(&self, connection: &mut PgConnection) -> Result<u64> {
        let (pid, timezone): (i32, String) =
            sqlx::query_as("SELECT pg_backend_pid(), current_setting('TimeZone')")
                .fetch_one(connection)
                .await?;
        assert_eq!(timezone, self.expected);
        self.pids.lock().unwrap().push(pid);
        if self.fail {
            bail!("timezone reconnect sentinel");
        }
        Ok(0)
    }
}

#[tokio::test]
#[ignore = "requires local PostgreSQL"]
async fn default_writer_keeps_sqlx_utc_timezone() -> Result<()> {
    let fixture = Fixture::new(true).await?;
    let writer = fixture.writer(timeouts());
    writer.check_ready().await?;
    let batch = TimezoneBatch {
        expected: "UTC",
        pids: Mutex::new(Vec::new()),
        fail: false,
    };
    assert_eq!(
        writer
            .write_transaction(Uuid::new_v4(), QUEUE, &batch)
            .await?,
        0
    );
    assert_eq!(batch.pids.lock().unwrap().len(), 1);
    drop(writer);
    fixture.close().await
}

#[tokio::test]
#[ignore = "requires local PostgreSQL"]
async fn configured_timezone_applies_to_both_paths_and_survives_reconnect() -> Result<()> {
    let fixture = Fixture::new(true).await?;
    let utc_writer = fixture.writer(timeouts());
    utc_writer.check_ready().await?;
    let utc_batch = TimezoneBatch {
        expected: "UTC",
        pids: Mutex::new(Vec::new()),
        fail: false,
    };
    utc_writer
        .write_transaction(Uuid::new_v4(), QUEUE, &utc_batch)
        .await?;
    let writer = utc_writer.clone().with_timezone("Europe/Moscow");
    let mut batch = TimezoneBatch {
        expected: "Europe/Moscow",
        pids: Mutex::new(Vec::new()),
        fail: false,
    };
    for _ in 0..2 {
        assert_eq!(
            writer
                .write_transaction(Uuid::new_v4(), QUEUE, &batch)
                .await?,
            0
        );
    }
    assert_eq!(writer.write_prepared(Uuid::new_v4(), QUEUE, || {
        Ok(PreparedBatch::new(
            "INSERT INTO records(value) SELECT CASE WHEN current_setting('TimeZone') = 'Europe/Moscow' THEN 3 ELSE 0 END FROM data_save_input",
            json!([]),
        ))
    }).await?, 1);
    let value: i32 = sqlx::query_scalar("SELECT value FROM records")
        .fetch_one(&fixture.pool)
        .await?;
    assert_eq!(value, 3);
    let failed_id = Uuid::new_v4();
    batch.fail = true;
    let error = writer
        .write_transaction(failed_id, QUEUE, &batch)
        .await
        .unwrap_err();
    assert!(format!("{error:#}").contains("timezone reconnect sentinel"));
    assert_eq!(fixture.receipt_count(failed_id).await?, 0);
    batch.fail = false;
    assert_eq!(
        timeout(WATCHDOG, writer.write_transaction(failed_id, QUEUE, &batch)).await??,
        0
    );
    let pids = batch.pids.into_inner().unwrap();
    assert_eq!(pids.len(), 4);
    assert_eq!(pids[0], pids[1]);
    assert_eq!(pids[1], pids[2]);
    assert_ne!(
        pids[2], pids[3],
        "failure must discard the dedicated connection"
    );
    utc_writer
        .write_transaction(Uuid::new_v4(), QUEUE, &utc_batch)
        .await?;
    let utc_pids = utc_batch.pids.into_inner().unwrap();
    assert_eq!(utc_pids.len(), 2);
    assert_eq!(
        utc_pids[0], utc_pids[1],
        "original clone keeps its UTC connection"
    );
    assert_ne!(
        utc_pids[0], pids[0],
        "configured clone opens its own connection"
    );
    drop(writer);
    drop(utc_writer);
    fixture.close().await
}

#[tokio::test]
#[ignore = "requires local PostgreSQL"]
async fn invalid_timezone_fails_readiness_without_writes() -> Result<()> {
    let fixture = Fixture::new(true).await?;
    let writer = fixture
        .writer(timeouts())
        .with_timezone("Not/A_Real_Timezone");
    let error = timeout(WATCHDOG, writer.check_ready()).await?.unwrap_err();
    let message = format!("{error:#}");
    assert!(message.contains("Not/A_Real_Timezone"), "{message}");
    assert_eq!(fixture.counts().await?, (0, 0));
    let receipts: i64 = sqlx::query_scalar("SELECT count(*) FROM data_save_batches")
        .fetch_one(&fixture.pool)
        .await?;
    assert_eq!(receipts, 0);
    drop(writer);
    fixture.close().await
}
